README.md

1. Added a link to the 14-hour python course
2. Added some awesome illustration links

Added some python and design resources!

---

README.md

I made some mistakes in the last push. Hopefully this fixes all of them 😃

Fix formatting issues from last push

---

README.md

Updated the android resources.

Added Android Resources

---

README.md

React resources

---

README.md

issue#13 Added React Resources in README.md

 Added React Resources

---

README.md

This is Jupyter notebook notes for intermediate learners.

Python intermediate notes

---

README.md

Hey @shahednasser , as mentioned in #18 , I had added SASS and LESS resources in `README.md` file

Added LESS and SASS resources

---

README.md

I have added the resources @shahednasser. Please review.

Added Java Resources

---

README.md

Add unity resources

---

README.md

Issue #1 
I have added new Angular and Vue resources. Please take a look at it.

Adding Angular and Vue resources

---

README.md

Issue #1 
I have added Express resources. Please take a look at it.

Adding Express Resources

---

README.md

Add PHP resources

---

CONTRIBUTING.md
README.md

Hey! I have added few resources and some attractive badges to both of your files. Kindly review and tell me if I should do something else. Considering merging it as well.

Added few resources and badges in both files. 

---

README.md

Added S.O.L.I.D. Principles around You in JavaScript under JavaScript

Added S.O.L.I.D. Principles around You, in JavaScript under JavaScript

---

README.md

Added testing category with a blog post on how to start your career in testing.

Added Testing Category

---

README.md

@shahednasser  Please review this

Added Resources: FOr CS50 , Intro to DataScience

---

README.md

Form a new category Open source in Others section and added resources for Open Source, Dynamic Programming and GitHub. Thank You!

Added new category Open Source and resources in Open Source, DP and GitHub

---

README.md

@shahednasser Please review this

Added Resources to Learn aout Dev ops Engineering

---

README.md

added a JS resource, also fixed the previous mistake.

30 days JS challenge

---

README.md

Issue #1 
I have added Git & GitHub resources.

Adding Git & GitHub resources

---

README.md

Added two resources for learning linux including course and article.

Added Linux resources

---

README.md

Added docker resources

---

README.md

A new category of nodejs has been added and very relevant sources has been added.

Added new category of nodejs.

---

README.md

Added a list of articles, video courses, and other important resources for typescript.
For issue #66

TypeScript Resources

---

README.md

I was going through my pull requests, cleaning up and came back here and noticed double lines under "Swift". I don't know if it was a mistake by me or someone else or whatever but my OCD made me want to fix it :)

fix double lines under Swift

---

README.md

Added ML resources and removed some extra spaces.

Added Machine-Learning Resources

---

README.md

Added Laravel Resources

---

README.md

Added Introduction to ricing under Linux

---

README.md

I had added few useful free learning resources.

Added few resources 

---

README.md

added new Flutter and GraphQl tutorial. issue #79

updated README.md with new tutorials

---

README.md

Added Automate the Boring Stuff with python - Free Book for learning python.
Lets celebrate hacktoberfest!

Added Automate the Boring Stuff with Python

---

README.md

this is with regards to issue #1

Added useful resources in Android

---

css/index.sass

add 10px of spacing to h2

---

README.md

1. Full Stack Javascript course from The Odin Project
2. Ruby and Ruby on Rails course from The Odin Project

Add Courses

---

README.md

Changing "To contribute, please check out our contribution guide here." to "To add a resource or contribute, please check out our contribution guide here."

#fixes 116 Update README.md

---

README.md

These notes are a free resource. They can be used as a stand alone guide, along with the videos or a quick reference for all the different parts of JavaScript like the different ways to declare a function.

Beginner JavaScript Notes + Reference by Wes Bos

---

README.md

Added Code Learning Free Courses Online Platform

Added New Website to learn programming languages free online

---

README.md

Added a blog- How to start with python.

Added How to start with Python

---

README.md

Updated readMe with new DevOps resources

Updated ReadME DevOps Section

---

README.md

added Git and CSS resources

---

README.md

Adding three amazing books that are available to read online:
- JavaScript for impatient programmers
- Building Front-End Web Apps with Plain JavaScript
- The Modern JavaScript Tutorial

Update README.md Javascript section

---

README.md

Docker curriculum ebook
Kubernetes Guide
Linux Kernel Ebook and interactive map

Added a few resources

---

README.md

Added a new freely available resource for the category "Design"

Added resource for Design Category

---

README.md

Added resource to show how to run graphics.h in vs code

Added VS Code trick in others section

---

README.md

Added Machine learning introductory primer

Added under machine learning

---

README.md

Hello there! :wave:
This pull request adds a new category to the list - [Go](https://github.com/golang/go).
I also added a new resource under Go - [Tour of Go](https://tour.golang.org/), which is a quick tour of the Go programming language.
Cheers!

Add Go category and Go resources

---

README.md

Hi! I have added 2 free for Design.
1. Geometric Shapes: https://tool.graphics/shapes
2. 3D-Icons: https://free3dicon.com/
Thanks.

Added Free Websites for Design

---

README.md

Adding my [blog](https://dev.to/saviomartin/20-killer-javascript-one-liners-94f) - [20 Killer JavaScript One Liners ☝️](https://dev.to/saviomartin/20-killer-javascript-one-liners-94f) written on dev.to that got highly popular there.

Feat ✨: Added a JavaScript Resource

---

README.md

I have added my own node js and vs code resources

added two resources by JOBIN-S

---

README.md

Added 30 seconds of code snippets website for javascript

Adding JavaScript Resource

---

README.md

Adding Kubernetes and Red Hat OpenShift resources, I think it would be a good addition to this repository

adding openshift, kubernetes and data science resources 

---

README.md

Hi there!
I added [Git - the simple guide](https://rogerdudler.github.io/git-guide/) which is an amazing Guide for beginners who are just getting started with Git!

Add Git Guide for beginners

---

README.md

Some learners like me prefer to learn things by reading the documentation and implementing the code by their own.
I added STL documentation for such users under the STL section of README.md

Added reading resource for C++ STL

---

README.md

- Fullstack 2021
- JavaScript Promises series
Many Thanks!

Add a couple of JavaScript resources

---

README.md

Added cheat sheets to the Data Science category.

Added Data Science resources

---

README.md

Adding a new illustration source on the design section

Adding a design resource

---

README.md

Hi, I added 4 Go resources that I found very useful in learning the language.
1. [Go by Example](https://gobyexample.com/)
2. [Gophercises: Free Coding Exercises for Budding Gophers](https://gophercises.com/)
3. [Justforfunc: Programming in Go](https://www.youtube.com/channel/UC_BzFbxG2za3bp5NRRRXJSw)
4. [Learn Go with Tests](https://quii.gitbook.io/learn-go-with-tests/)

Added Go resources

---

README.md

- How to start as a beginner (Video Tutorials)
- How to automate the Boring Stuff with Python
- Various Algorithm Implementations using Python

Added new Python Resources 

---

README.md

Add undesign website to Design resources

feat: add undesign

---

README.md

- Added remove.bg, ls.graphics and Unsplash. Very useful tools for designers and video editors to get things done quickly.
- Added description for unDraw

Added 3 Design Resources

---

README.md

adding tools section and tiny helpers

feat: adding tools section

---

README.md

This PR includes a resource called **Git Exercises by Fracz**.
With this platform, you can learn and practice Git and discover its features you might haven't been aware of. With all the exercises provided, you will rapidly become a Git Master!
Kindly consider this PR as a part of Hacktoberfest 2021.

Add resource for GIT

---

README.md

Add Oh My Git (#1) to Git Category
Oh My Git is a free and helpful game to learn git.

Added Oh My Git game under Git Category

---

README.md

I've added a Webpack Getting Started article which I find quite easy to understand (It's the one from which I learned it).
I've also updated the link for CS50 so it redirects to the current year of the course.
Thank You : )

Added Webpack Guide & Updated CS50 link

---

README.md

Found this repo interesting so added a framework that I found smooth to start off as a beginner.

Added svelte path

---

README.md

Added Object Oriented Programming in Java course by Coursera

Added Object Oriented Programming in Java course by Coursera

---

README.md

Added ReactJS Tutorial for Beginners tutorials playlist for beginners by Codevolution

Added ReactJS Tutorial under React Category

---

README.md

I've added the Android Basics with Kotlin course from Google Developers. It is relatively new. 
The participants earn badges as they progress the course that show up in their Google Developer Profile. 
It also helps to prepare for Android Associate Developer Certificate exam.

Added Android Basics with Kotlin Course

---

README.md

Introduction to html

---

README.md

1. Added DSA + interview course for C++
2. Added Free resource to learn C++

Added Resources for C++

---

README.md

Added Docker Labs & Docker Cheat Sheet

Adding Resources for Docker

---

README.md

- Added resources for understanding git commands in an easy way
- Added resources related to the best GitHub practices for the developers.

Added resources for learning Git

---

README.md

Add multiple resources to learn from if you want to learn rust.

Add rust resources

---

README.md

I've added a great free resource provided by LWN that has everything in it regarding Linux Driver Development

added resource for Linux Driver Development

---

README.md

Hi,
I have added Terraform resources to this wonderful repo
PS: First time participating on Hacktoberfest 😊

Added Terraform Resource

---

README.md

The Repo contains many ML algos written from scratch which can be used by many to understand the basic concepts behind each algorithm

Adding ML algos from scratch repository

---

README.md

Added link for using Flutter packages.

added Flutter packages

---

README.md

Added C++ resources to help the community flourish

Added C++ resources to help the community flourish

---

README.md

Also added FreeCodeCamp section under node,js category, added design patterns link under PHP category

Added Laravel Daily under Laravel category

---

README.md

This course is mostly for Spanish speakers, Leonidas Esteban is a great teacher.

Add css grid course

---

README.md

Added a full course of TypeScript for beginners that covers the latest updates till 2021.

Add TypeScript full course for beginners

---

README.md

added the free hosting websites to `README.md`

added free hosting websites

---

README.md

Fix Ruby & Sass naming

---

README.md

Added two youtube playlists for Golang. One is for begineers and another playlist is for intermediate and advance gophers.

Added resources for Go

---

README.md

ADD: Eslint & Prettier docs as tools

---

css/index.sass

Fix #342 
@shahednasser, kindly check to see if I did the right thing. This is my first time working with Sass 😅

Fix hover style link in dark mode

---

css/index.sass

Made scroll behaviour smooth

---

README.md

Tool: [ray.so](https://ray.so/)

Add a new tool

---

README.md

@shahednasser 
I have added a link to "20+ Web Projects With Vanilla JavaScript" in the JavaScript category.
This is my first pull request, so please advise me if I'm doing it wrong.
I hope my contribution will benefit the repository.

Add 20+ Web Projects With Vanilla JavaScript for JavaScript

---

README.md

Hi I have updated Readme.md. Please check

Added Git and Github tutorial in Readme.md

---

README.md

fixed a minor bug

---

README.md

fixed [#354](https://github.com/shahednasser/awesome-resources/issues/354#issue-1112202239)

Fixed a broken link in JavaScript section.

---

README.md

Added "Back to Index" link between C and C++

---

CONTRIBUTING.md

Added note in contributing guidelines

---

README.md

[Squircley](https://squircley.app/): Start creating beautiful organic shapes ready to use for logos, icons and background images

add new tool

---

README.md

- :wrench: [Whirl](https://whirl.netlify.app/) : CSS loading animations with minimal effort!

add new CSS tool

---

README.md

This a completely free DevOps Bootcamp and it is in progress.

Added the link to a free Devops Bootcamp

---

README.md

add 90 Days Of DevOps

---

README.md

Added HTML and Javascript learning resources.

---

README.md

Added SASS Tutorial playlist from Youtube.  [SASS Tutorial (Build Your Own CSS Library)](https://youtube.com/playlist?list=PL4cUxeGkcC9jxJX7vojNVK-o8ubDZEcNb)

Added SASS Tutorial Playlist

---

README.md

[BrandBird](https://www.brandbird.app/): An image editor for busy SaaS founders, who build in public!

Add new tool 🔧  : BrandBird

---

README.md

Added a beginner-friendly Data Structures tutorial. [Scalar]
Well written articles suited for beginners.

Data Structures Tutorial (Beginner)

---

README.md

Added a website that contain a very useful list of tutorials on different topics in Operating Systems.

Added to Operating Systems.

---

README.md

Added a C++ Standard Template Library youtube video specially for competitive programming .
CP(competitive programming) is a trending programming sport in India where people mainly use C++ for CP and there is a lot of usage of C++ STL for competitive programming.
So I added a one shot video by Raj vikram aditya ( a Google SDE and a famous competitive programmer of india) who taught about STL

C++ resource for competitive programming

---

README.md

=>  Adding a very useful article on “Best tools for DevOps” 
=>  Changing the title name of an article from “Dev Op Terms” to “10 Essential DevOps terms to know” as it's a more appropriate one

Adding a very useful article and improving the title of an article

---

README.md

I worked through the issue #388

Pull request: fix issue #388

---

README.md

I made 2 changes:
Change 1: I added a new tips link that everyone learning HTML should be aware of. 
Change 2: Rearranged the HTML list so that the video links are together.

added a new tips link for HTML and rearranged the HTML list 

---

README.md

Added **React Native** Tutorial For Beginners Link at the End of the **React Native** Category.

Added React Native Tutorial Playlist.

---

README.md

Added a free IBM Certification course link for deep learning

Added a free IBM Certification course for deep learning

---

README.md

Added **Kubernetes** in the Content and Added the **100 Days of Kubernetes** Link at the Bottom of the Kubernetes Category.

Added Kubernetes in the Content.

---

README.md

I have added a link to "Effective Go" to the Golang category.
This is my first pull request, so please advise if I am wrong.
I hope my contribution will benefit the repository.

Added "Effective Go" to Go resources

---

README.md

flexbox froggy is a simple website to practice flexbox and master it, very much useful to judge one's skill in flexbox.

Added "CSS Flexbox Froggy" to CSS Resources

---

README.md

I have updated the Free-Hosting Section to its Proper Category in the Contents section which is F-Category according to alphabet order

Updated the Free-Hosting Section Position

---

README.md

This change is to introduce Networking category along with fundamental of Networking resource. Reason for adding this resource is because its easy to follow and takes networking concepts from very basic to advance level.

Added networking category with resource on fundamental of networking

---

README.md

Hey, I had added 3 awesome resources to the Design Section.
Could you please add the hacktoberfest accepted label to this pr and merge?
Thanks.

Added some awesome Design Resources

---

README.md

Added a free online book "Operating Systems: Three Easy Pieces" under Operating Systems.

Add an operating system book

---

README.md

A YouTube tutorial explaining the basics of React in a visual-aided, crisp manner is added as a resource.

Added React resource

---

README.md

a free course about an important topic in Computer Science called Compilers & Interpreters, this course provides the theory behind compilers and the required knowledge to build a new programming language

add: Edx course to learn how Compilers works

---

README.md

Added new 4 good resources about Laravel
- :books: [Laravel Tutorial](https://www.javatpoint.com/laravel)
- :books: [Laravel News](https://laravel-news.com)
- :books: [LaraShout: Laravel Tutorials and Guides](https://www.larashout.com)
- :bulb: [Laravel Daily](https://laraveldaily.com)

Added new resources under Laravel

---

README.md

a free course provided by Udacity teaches the Kotlin programming language which is essential in modern Native Android Development

add: Udacity course to Learn Kotlin Fundamentals

---

README.md

**Supersedes #446**
This pull request adds a new category to the list - Regular Expressions
I personally believe Regular Expressions (or regex, or regexp, call it whatever you will) are incredibly helpful for any programmer, so I've added this category.
I have also taken the liberty of adding a few relevant resources, including tools and short courses, under the same topic
Cheers!

feat: add regular expression category and resources

---

README.md

Add Flutter resources about [Bloc](https://bloclibrary.dev/)

add: Flutter Bloc resources

---

README.md

Included the best playlist for learning Dynamic Programming.

Added the resource for Dyanmic Programming.

---

README.md

as mentioned in #1 ,
I have added resources for multiple topics -blockchain, DevOps, database, PostgreSQL, etc. 
let me know if there are any changes to be made :)

added Resources on multiple topics

---

README.md

Add Knights of the Flexbox Table link which is a fun dungeon based game to learn flexbox and is a great progression after Flexbox Froggy. Also added CSS validator link.

update: Add CSS resources on README

---

README.md

At the end of the JavaScript Category, I included the JavaScript Visualizer 9000.

Add JavaScript Visualizer

---

README.md

Added Material Design Lite to CSS

---

README.md

Added Pure to CSS

---

README.md

Added Power Automate category to Readme.md and included the link to Microsoft Power Automate documentation

Added Power Automate category to Readme.md

---

README.md

Added Skeleton to CSS

---

README.md

Added UIkit to CSS

---

README.md

Added Cyclic to Free Hosting

---

README.md

At the end of the Algorithms Category, I included the Algorithm Visualizer.

Add Algorithm Visualizer

---

README.md

Added resources for web design

Added resources for Web Design

---

README.md

Create and share beautiful images of your source code. (An alternative of [ray.so](https://ray.so/))
Please review and merge it.

Added Carbon for creating image of source code

---

README.md

LearnWeb3 DAO is a free, high-quality, holistic education platform to become a web3 developer in 2022. Thanks for reading my Pull Request

Added LearnWeb3 DAO to Readme.md

---

README.md

Added Adaptable to Free Hosting

---

README.md

Added a small resource to the MySQL section.
This is my first pull request to open source, thank you in advance.

Add MySQL resource

---

README.md

Josh W Comeau - Understanding layout algorithms.

Add css resource

---

README.md

let me know if you have any questions or concerns. thanks!

added open ai gpt-3 machine learning documentation

---

README.md

Hey there,
I've added a few additional resources under Testing, Web Accessibility, and Others. Hope these help!

Adding additional resources to the README

---

README.md

new book has been added

---

README.md

These blog posts include useful features like live share, WSL2 integration, and remote SSH

Add Blog Posts on useful VS Code Features

---

README.md

This PR adds a youtube series of tutorials as well as the famous Berkely AI Pacman project which is a full hands-on project.

Add AI Hands-On Tutorials

---

README.md

This PR adds the system design primer which is one of the most comprehensive resources for starting to learn system design and prepare for interviews.

Add System Design Primer

---

README.md

Added [Figma Community](https://www.figma.com/community/) in Design
> Discover inspiring portfolios, presentations, mockups, and more or publish live design files that anyone in the world can inspect, remix, and learn from.
Please review and merge it.

Added Figma Community resource in Design

---

README.md

added advanced data structures playlist

added advanced data stuctures playlist

---

README.md

Added the Computer networking playlist by Gate Smashers .

Added Computer Networking Playlist

---

README.md

Hi, I've created a new branch from the master and made changes there. Thank you.

Added GLSL category and new books in it

---

README.md

Added a resource that has some amazing nice projects that will help the beginner to get started and learning react to be easy 😊😄

react beginner project video

---

README.md

- Add Documentation by John Gruber, the Creator of Markdown, 
- Add Reference Sheet made by Squarespace

Add Markdown resources

---

README.md

Add - tmux cheatsheet to README.md under "Other Resources" section

---

README.md

Mt PR for Hactoberfest hope it gets merged😊

Added a flask section to the README.md

---

README.md

#hacktoberfest #hacktoberfest2022 @shahednasser 
Added Django Rest Framework Tutorial

Added Django Rest Framework tutorial
